print("Hello World!")
print("Malik Usman")
print("Malik Usman Ahmad")
print(1,2,3)
print("Hi this is the test of \nnew line start")
print("This line indicate the \t tab character")
print("Hello","World","Test",sep=",")
print(22,33,44,sep="-")
print('"Hello this is double qoute test"')
print('This is backslash \\ test in python')
print("I'm 25 years Old :)")
print("This is the test of string and" , 5)
print(1)
print(2)
print(3)
print(4)
print(5)
print("usman")